# Generated by Django 3.0.6 on 2020-05-20 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular secret across whole storage', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a secret name', max_length=200)),
                ('content', models.CharField(help_text='Enter a secret content', max_length=200)),
                ('comment', models.TextField(blank=True, help_text='Enter a secret comment', max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a team name', max_length=200)),
                ('members', models.ManyToManyField(help_text='Select team members', to=settings.AUTH_USER_MODEL)),
                ('secrets', models.ManyToManyField(help_text='Select team secrets', to='storage.Secret')),
            ],
        ),
    ]
