# Generated by Django 3.0.6 on 2020-05-20 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Select team members', null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='secrets',
            field=models.ManyToManyField(blank=True, help_text='Select team secrets', null=True, to='storage.Secret'),
        ),
    ]
