# Generated by Django 3.0.6 on 2020-05-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20200520_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secret',
            old_name='user',
            new_name='owner',
        ),
    ]
