# Generated by Django 3.0.6 on 2020-05-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20200520_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('can_manage_group', 'Manage a group'),)},
        ),
    ]
